apiVersion: v1
kind: Service
metadata:
  name: denodo-vdp-service
spec:
  selector:
    app: denodo-vdp-app
  ports:
  - name: svc-denodo
    protocol: "TCP"
    port: 9999
    targetPort: denodo-port
  - name: svc-rmi-r
    protocol: "TCP"
    port: 9997
    targetPort: jdbc-rmi-rgstry
  - name: svc-rmi-f
    protocol: "TCP"
    port: 9995
    targetPort: jdbc-rmi-fctory
  - name: svc-odbc
    protocol: "TCP"
    port: 9996
    targetPort: odbc
  - name: svc-web
    protocol: "TCP"
    port: 9090
    targetPort: web-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: denodo-vdp-deployment
spec:
  selector:
    matchLabels:
      app: denodo-vdp-app
  replicas: 1
  template:
    metadata:
      labels:
        app: denodo-vdp-app
    spec:
      hostname: denodo-vdp-hostname
      containers:
      - name: denodo-vdp-container
        image: gar.io/<PROJECT_ID>/denodo-vdp-platform
        command: ["./denodo-vdp-container-start.sh"]
        args: ["--vqlserver"]
        env:
        - name: FACTORY_PORT
          value: "8995"
        ports:
        - name: denodo-port
          containerPort: 9999
        - name: jdbc-rmi-rgstry
          containerPort: 9997
        - name: jdbc-rmi-fctory
          containerPort: 9995
        - name: odbc
          containerPort: 9996
        - name: web-container
          containerPort: 9090
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /opt/denodo/sm/SolutionManager.properties /opt/denodo/conf/SolutionManager.properties"]        
        volumeMounts:
        - name: config-volume
          mountPath: /opt/denodo/sm
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: solution-manager
          items:
          - key: SolutionManager.properties
            path: SolutionManager.properties