apiVersion: v1
kind: Service
metadata:
  name: denodo-vdp-service
spec:
  selector:
    app: denodo-vdp-app
  ports:
  - name: svc-denodo
    protocol: "TCP"
    port: 8999
    targetPort: denodo-port
  - name: svc-rmi-r
    protocol: "TCP"
    port: 8997
    targetPort: jdbc-rmi-rgstry
  - name: svc-rmi-f
    protocol: "TCP"
    port: 8995
    targetPort: jdbc-rmi-fctory
  - name: svc-odbc
    protocol: "TCP"
    port: 8996
    targetPort: odbc
  - name: svc-web
    protocol: "TCP"
    port: 8090
    targetPort: web-container
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: denodo-shared-deployment
spec:
  selector:
    matchLabels:
      app: denodo-vdp-app
  replicas: 2
  template:
    metadata:
      labels:
        app: denodo-vdp-app
    spec:
      hostname: denodo-vdp-hostname
      containers:
      - name: denodo-vdp-container
        image: denodo-platform:8.0-latest
        command: ["./denodo-vdp-container-start.sh"]
        args: ["--vqlserver"]
        env:
        - name: FACTORY_PORT
          value: "8995"
        ports:
        - name: denodo-port
          containerPort: 9999
        - name: jdbc-rmi-rgstry
          containerPort: 9997
        - name: jdbc-rmi-fctory
          containerPort: 8995
        - name: odbc
          containerPort: 9996
        - name: web-container
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /opt/denodo/conf/denodo.lic
          subPath: denodo.lic
      volumes:
      - name: config-volume
        configMap:
          name: denodo-license