name: Build and Push Denodo Docker Image to GCP
on:
  push:
    branches: [ main ]
jobs:
  build-push-gar:
    name: Build and Push to GCP Artifact Repository
    runs-on: uduntu-latest
    env:
      IMAGE_NAME: denodo-ons
      PROJECT_ID: dm-denodo-gcp-v1


